/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/task-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTaskCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTasks"];
        put?: never;
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/discovered-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get: operations["listDiscoveredTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get: operations["listTaskExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executions/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get: operations["listTaskComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/comments/search": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchTaskComments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{taskId}/comment-exports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        get: operations["listCommentExports"];
        put?: never;
        post: operations["createCommentExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comment-exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["getCommentExport"];
        put?: never;
        post?: never;
        delete: operations["cancelCommentExport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comment-exports/{exportId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get: operations["downloadCommentExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/{credentialId}/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["replaceCredentialSecret"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/{credentialId}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PositiveId: string;
        UnsignedId: string;
        /** @enum {string} */
        SourceType: "VIDEO" | "DYNAMIC" | "CREATOR";
        /** @enum {string} */
        TaskKind: "CONTENT_COMMENTS" | "CREATOR_WATCH";
        /** @enum {string} */
        CollectionMode: "FOLLOW_ONLY" | "BACKFILL_ONLY";
        /** @enum {string} */
        DesiredState: "ACTIVE" | "PAUSED";
        /** @enum {string} */
        ScheduleType: "ADAPTIVE" | "CRON" | "MANUAL";
        /** @enum {string} */
        RuntimeState: "IDLE" | "QUEUED" | "RUNNING" | "RETRY_WAIT" | "ERROR" | "COMPLETED";
        /** @enum {string} */
        HealthStatus: "UNKNOWN" | "HEALTHY" | "DEGRADED" | "ERROR";
        /** @enum {string} */
        ExecutionStatus: "QUEUED" | "RUNNING" | "RETRY_WAIT" | "SUCCEEDED" | "FAILED" | "CANCELLED";
        /**
         * @default ALL
         * @enum {string}
         */
        CommentReplyScope: "ALL" | "ROOT" | "REPLIES";
        /**
         * @default CTIME_DESC
         * @enum {string}
         */
        CommentSort: "CTIME_DESC" | "CTIME_ASC";
        /** @enum {string} */
        CommentExportFormat: "CSV" | "JSONL";
        /** @enum {string} */
        CommentExportColumn: "RPID" | "PARENT_RPID" | "MID" | "UNAME" | "AVATAR" | "CURRENT_LEVEL" | "CONTENT" | "CTIME";
        /** @enum {string} */
        CommentExportStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "EXPIRED";
        /** @enum {string|null} */
        ExecutionPhase: "RESOLVING_SOURCE" | "FETCHING_COMMENTS" | "PERSISTING_COMMENTS" | "WAITING_RATE_LIMIT" | "SCHEDULING_NEXT" | null;
        AdminUser: {
            username: string;
            displayName: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        TaskCapability: {
            kind: components["schemas"]["TaskKind"];
            sourceTypes: components["schemas"]["SourceType"][];
            collectionModes: components["schemas"]["CollectionMode"][];
        };
        ResolveSourceRequest: {
            sourceType: components["schemas"]["SourceType"];
            input: string;
        };
        TaskSource: {
            type: components["schemas"]["SourceType"];
            id: string;
            title: string;
        };
        /** @enum {string} */
        TaskOrigin: "MANUAL" | "DISCOVERED";
        /** @enum {string} */
        TaskRelationMode: "MANAGED" | "REFERENCED";
        /**
         * @default PRIMARY
         * @enum {string}
         */
        TaskScope: "PRIMARY" | "MANAGED" | "ALL";
        ParentTaskReference: {
            taskId: components["schemas"]["PositiveId"];
            name: string;
        };
        DiscoveredTaskSummary: {
            total: number;
            neverStarted: number;
            queuedOrRunning: number;
            retryWaiting: number;
            errors: number;
            commentsInserted24h: number;
            /** Format: date-time */
            newestDiscoveredAt: string | null;
        };
        SourceResolution: {
            source: components["schemas"]["TaskSource"];
            accessible: boolean;
            message: string | null;
        };
        TaskSummary: {
            id: components["schemas"]["PositiveId"];
            version: number;
            name: string;
            kind: components["schemas"]["TaskKind"];
            source: components["schemas"]["TaskSource"];
            collectionMode: components["schemas"]["CollectionMode"];
            desiredState: components["schemas"]["DesiredState"];
            runtimeState: components["schemas"]["RuntimeState"];
            health: components["schemas"]["HealthStatus"];
            scheduleLabel: string;
            credentialName: string;
            /** Format: date-time */
            lastSuccessAt: string | null;
            /** Format: date-time */
            nextRunAt: string | null;
            latestInsertedCount: number;
            /** Format: date-time */
            updatedAt: string;
            origin: components["schemas"]["TaskOrigin"];
            relationMode: components["schemas"]["TaskRelationMode"] | null;
            parentTask: components["schemas"]["ParentTaskReference"] | null;
            discoveredSummary: components["schemas"]["DiscoveredTaskSummary"] | null;
        };
        TaskDetail: components["schemas"]["TaskSummary"] & {
            remark: string | null;
            /** Format: date-time */
            createdAt: string;
            watchedContentTypes: ("VIDEO" | "DYNAMIC")[];
        };
        DiscoveredTaskItem: {
            task: components["schemas"]["TaskSummary"];
            commentsTotal: number;
            commentsInserted24h: number;
            /** Format: date-time */
            firstDiscoveredAt: string;
            /** Format: date-time */
            lastDiscoveredAt: string;
            firstDiscoveredExecutionId: components["schemas"]["PositiveId"] | null;
            lastDiscoveredExecutionId: components["schemas"]["PositiveId"] | null;
        };
        TaskSourceInput: {
            type: components["schemas"]["SourceType"];
            input: string;
        };
        TaskScheduleInput: {
            strategy: components["schemas"]["ScheduleType"];
            cronExpression?: string | null;
            /** @constant */
            zoneId: "Asia/Shanghai";
        };
        CreateTaskRequest: {
            name: string;
            kind: components["schemas"]["TaskKind"];
            source: components["schemas"]["TaskSourceInput"];
            collectionMode: components["schemas"]["CollectionMode"];
            credentialProfileId: components["schemas"]["PositiveId"];
            schedule: components["schemas"]["TaskScheduleInput"];
            watchedContentTypes?: ("VIDEO" | "DYNAMIC")[];
            desiredState: components["schemas"]["DesiredState"];
            startNow: boolean;
            remark?: string | null;
        };
        TaskExecution: {
            id: components["schemas"]["PositiveId"];
            taskId: components["schemas"]["PositiveId"];
            /** @enum {string} */
            trigger: "SCHEDULED" | "MANUAL" | "DISCOVERED";
            status: components["schemas"]["ExecutionStatus"];
            phase: components["schemas"]["ExecutionPhase"];
            pagesFetched: number;
            commentsDiscovered: number;
            commentsInserted: number;
            duplicatesSkipped: number;
            retryCount: number;
            cursor: string | null;
            errorSummary: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            lastHeartbeatAt: string | null;
        };
        Comment: {
            id: components["schemas"]["PositiveId"];
            rpid: components["schemas"]["PositiveId"];
            parentRpid: components["schemas"]["PositiveId"] | null;
            mid: string;
            uname: string | null;
            avatar: string | null;
            currentLevel: number | null;
            content: string | null;
            /** Format: date-time */
            ctime: string;
        };
        CommentFilter: {
            keyword?: string | null;
            mid?: string | null;
            uname?: string | null;
            levelMin?: number | null;
            levelMax?: number | null;
            /** @default false */
            unknownLevelOnly: boolean;
            /** Format: date-time */
            ctimeFrom?: string | null;
            /** Format: date-time */
            ctimeBefore?: string | null;
            rpid?: components["schemas"]["PositiveId"] | null;
            parentRpid?: components["schemas"]["PositiveId"] | null;
            replyScope?: components["schemas"]["CommentReplyScope"];
        };
        CommentSearchRequest: {
            filter: components["schemas"]["CommentFilter"];
            sort?: components["schemas"]["CommentSort"];
            cursor?: string | null;
            /** @default 50 */
            limit: number;
            /** @default false */
            includeTotal: boolean;
        };
        CommentSearchPage: {
            items: components["schemas"]["Comment"][];
            nextCursor: string | null;
            total: number | null;
        };
        CreateCommentExportRequest: {
            filter: components["schemas"]["CommentFilter"];
            sort?: components["schemas"]["CommentSort"];
            format: components["schemas"]["CommentExportFormat"];
            columns?: components["schemas"]["CommentExportColumn"][];
        };
        CommentExportJob: {
            id: components["schemas"]["PositiveId"];
            taskId: components["schemas"]["PositiveId"];
            status: components["schemas"]["CommentExportStatus"];
            format: components["schemas"]["CommentExportFormat"];
            columns: components["schemas"]["CommentExportColumn"][];
            rowsWritten: number;
            bytesWritten: number;
            downloadReady: boolean;
            errorCode: string | null;
            errorSummary: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            finishedAt: string | null;
            /** Format: date-time */
            expiresAt: string;
        };
        CredentialProfile: {
            id: components["schemas"]["PositiveId"];
            name: string;
            enabled: boolean;
            valid: boolean;
            /** Format: date-time */
            lastValidatedAt: string | null;
        };
        ReplaceCredentialSecretRequest: {
            secret: string;
        };
        DashboardSummary: {
            activeTasks: number;
            primaryActiveTasks: number;
            managedActiveTasks: number;
            runningTasks: number;
            retryWaitingTasks: number;
            commentsInserted24h: number;
            recentFailures: number;
        };
        SystemSummary: {
            /** @enum {string} */
            api: "UP" | "DEGRADED" | "DOWN";
            /** @enum {string} */
            database: "UP" | "DOWN";
            /** @enum {string} */
            bilibili: "UP" | "DEGRADED" | "DOWN";
            schedulerEnabled: boolean;
            schedulerActive: number;
            workerActive: number;
            workerPoolSize: number;
            workerQueueSize: number;
            sseConnections: number;
            recentFailureCount: number;
            rateLimitedCount: number;
            /** Format: date-time */
            measuredAt: string;
        };
        LiveEvent: {
            eventId: components["schemas"]["UnsignedId"];
            /** @enum {string} */
            type: "task.updated" | "execution.updated" | "comments.appended" | "system.updated" | "heartbeat";
            /** Format: date-time */
            occurredAt: string;
            sequence: number;
            taskId: components["schemas"]["PositiveId"] | null;
            executionId: components["schemas"]["PositiveId"] | null;
            data: {
                [key: string]: unknown;
            };
        };
        TaskPage: {
            items: components["schemas"]["TaskSummary"][];
            /** @description 下一页的不透明任务边界；为空表示没有下一页。 */
            nextCursor: string | null;
            total: number;
        };
        DiscoveredTaskPage: {
            items: components["schemas"]["DiscoveredTaskItem"][];
            nextCursor: string | null;
            total: number;
        };
        ExecutionPage: {
            items: components["schemas"]["TaskExecution"][];
            nextCursor: string | null;
            total: number;
        };
        CommentPage: {
            items: components["schemas"]["Comment"][];
            nextCursor: string | null;
            total: number;
        };
        ApiProblem: {
            /** Format: uri */
            type?: string | null;
            title?: string | null;
            status: number;
            code: string;
            detail: string;
            traceId?: string | null;
            fieldErrors?: {
                [key: string]: string;
            };
            existingTaskId?: components["schemas"]["PositiveId"] | null;
        };
    };
    responses: {
        /** @description 请求格式错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description 未登录或凭据错误 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description CSRF 失效或来源域名被禁止 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description 重复任务、活动执行或幂等冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description 导出任务或文件已过期并被清理 */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description 参数验证失败 */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description 请求过于频繁 */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description Bilibili 上游响应异常 */
        UpstreamFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description 数据库或上游暂不可用 */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
    };
    parameters: {
        TaskId: components["schemas"]["PositiveId"];
        ExecutionId: components["schemas"]["PositiveId"];
        CredentialId: components["schemas"]["PositiveId"];
        ExportId: components["schemas"]["PositiveId"];
        /** @description 服务端返回的不透明分页边界；客户端必须原样回传，不得解析或自行构造。 */
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前管理员 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出登录 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTaskCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可创建的任务组合 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCapability"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    resolveSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveSourceRequest"];
            };
        };
        responses: {
            /** @description 规范化后的来源 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResolution"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务页摘要 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                query?: string;
                sourceType?: components["schemas"]["SourceType"];
                collectionMode?: components["schemas"]["CollectionMode"];
                runtimeState?: components["schemas"]["RuntimeState"];
                health?: components["schemas"]["HealthStatus"];
                scope?: components["schemas"]["TaskScope"];
                /** @description 服务端返回的不透明分页边界；客户端必须原样回传，不得解析或自行构造。 */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description 已创建；相同幂等请求会返回原任务 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDiscoveredTasks: {
        parameters: {
            query?: {
                query?: string;
                sourceType?: "VIDEO" | "DYNAMIC";
                runtimeState?: components["schemas"]["RuntimeState"];
                health?: components["schemas"]["HealthStatus"];
                /** @description 服务端返回的不透明分页边界；客户端必须原样回传，不得解析或自行构造。 */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 该 UP 主监控任务发现的内容及采集状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveredTaskPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    pauseTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 暂停后的任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resumeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 恢复后的任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    runTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已排队的执行 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskExecution"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    listTaskExecutions: {
        parameters: {
            query?: {
                /** @description 服务端返回的不透明分页边界；客户端必须原样回传，不得解析或自行构造。 */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 执行历史分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 单次执行详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskExecution"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTaskComments: {
        parameters: {
            query?: {
                /** @description 服务端返回的不透明分页边界；客户端必须原样回传，不得解析或自行构造。 */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前任务独立评论表的游标分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    searchTaskComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentSearchRequest"];
            };
        };
        responses: {
            /** @description 固定快照内的筛选评论分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentSearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
        };
    };
    listCommentExports: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前任务最近的评论导出任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentExportJob"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    createCommentExport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                taskId: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentExportRequest"];
            };
        };
        responses: {
            /** @description 已创建异步导出任务；相同幂等请求返回原任务 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentExportJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    getCommentExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评论导出任务状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentExportJob"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelCommentExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已请求取消；终态任务保持不变 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["Gone"];
            422: components["responses"]["Unprocessable"];
        };
    };
    downloadCommentExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 解密后的 CSV 或 JSONL 文件；响应禁止缓存 */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/x-ndjson": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["Gone"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    listCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 脱敏凭据列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialProfile"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    replaceCredentialSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: components["parameters"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceCredentialSecretRequest"];
            };
        };
        responses: {
            /** @description 已保存 Cookie 原文，响应不返回 Cookie 内容 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    validateCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: components["parameters"]["CredentialId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验证后的凭据状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["UpstreamFailure"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSystemSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 脱敏运行摘要 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    subscribeEvents: {
        parameters: {
            query?: {
                afterSequence?: components["schemas"]["UnsignedId"];
            };
            header?: {
                "Last-Event-ID"?: components["schemas"]["UnsignedId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 持久化事件重放及实时 SSE；事件 data 结构为 LiveEvent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
