CREATE TABLE app.credential_profile (
    credential_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_key varchar(64) NOT NULL,
    display_name varchar(128) NOT NULL,
    credential_type varchar(32) NOT NULL DEFAULT 'BILIBILI_COOKIE',
    enabled boolean NOT NULL DEFAULT false,
    encrypted_cookie text,
    encrypted_refresh_token text,
    validation_status varchar(24) NOT NULL DEFAULT 'UNCONFIGURED',
    last_validated_at timestamptz,
    last_validation_message text,
    secret_version integer NOT NULL DEFAULT 0,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_credential_profile_key UNIQUE (credential_key),
    CONSTRAINT ck_credential_profile_key
        CHECK (credential_key ~ '^[a-z][a-z0-9_-]{0,63}$'),
    CONSTRAINT ck_credential_profile_type
        CHECK (credential_type IN ('BILIBILI_COOKIE')),
    CONSTRAINT ck_credential_profile_validation_status
        CHECK (validation_status IN ('UNCONFIGURED', 'UNKNOWN', 'VALID', 'INVALID', 'EXPIRED')),
    CONSTRAINT ck_credential_profile_enabled_secret
        CHECK (NOT enabled OR encrypted_cookie IS NOT NULL),
    CONSTRAINT ck_credential_profile_versions
        CHECK (secret_version >= 0 AND version >= 0)
);

CREATE TRIGGER trg_credential_profile_updated_at
BEFORE UPDATE ON app.credential_profile
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

INSERT INTO app.credential_profile (
    credential_key,
    display_name,
    enabled,
    encrypted_cookie,
    encrypted_refresh_token,
    validation_status
) VALUES (
    'default',
    'Default',
    false,
    NULL,
    NULL,
    'UNCONFIGURED'
);

CREATE TABLE app.task_definition (
    task_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name varchar(255) NOT NULL,
    task_type varchar(32) NOT NULL,
    source_type varchar(16) NOT NULL,
    source_id varchar(128) NOT NULL,
    collection_mode varchar(24) NOT NULL DEFAULT 'FOLLOW_ONLY',
    desired_state varchar(16) NOT NULL DEFAULT 'ACTIVE',
    schedule_type varchar(16) NOT NULL DEFAULT 'ADAPTIVE',
    cron_expression varchar(128),
    credential_profile_id bigint,
    source_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    schedule_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    remarks text,
    last_execution_at timestamptz,
    next_execution_at timestamptz,
    version bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT fk_task_definition_credential
        FOREIGN KEY (credential_profile_id)
        REFERENCES app.credential_profile (credential_profile_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_task_definition_source_mode
        UNIQUE (task_type, source_type, source_id, collection_mode),
    CONSTRAINT ck_task_definition_name
        CHECK (btrim(task_name) <> ''),
    CONSTRAINT ck_task_definition_source_id
        CHECK (btrim(source_id) <> ''),
    CONSTRAINT ck_task_definition_task_type
        CHECK (task_type IN ('CONTENT_COMMENTS', 'CREATOR_WATCH')),
    CONSTRAINT ck_task_definition_source_type
        CHECK (source_type IN ('VIDEO', 'DYNAMIC', 'CREATOR')),
    CONSTRAINT ck_task_definition_task_source
        CHECK (
            (task_type = 'CONTENT_COMMENTS' AND source_type IN ('VIDEO', 'DYNAMIC'))
            OR (task_type = 'CREATOR_WATCH' AND source_type = 'CREATOR')
        ),
    CONSTRAINT ck_task_definition_collection_mode
        CHECK (collection_mode IN ('FOLLOW_ONLY', 'BACKFILL_ONLY')),
    CONSTRAINT ck_task_definition_creator_mode
        CHECK (task_type <> 'CREATOR_WATCH' OR collection_mode = 'FOLLOW_ONLY'),
    CONSTRAINT ck_task_definition_desired_state
        CHECK (desired_state IN ('ACTIVE', 'PAUSED')),
    CONSTRAINT ck_task_definition_schedule_type
        CHECK (schedule_type IN ('ADAPTIVE', 'CRON', 'MANUAL')),
    CONSTRAINT ck_task_definition_cron
        CHECK (
            (schedule_type = 'CRON' AND NULLIF(btrim(cron_expression), '') IS NOT NULL)
            OR (schedule_type <> 'CRON' AND cron_expression IS NULL)
        ),
    CONSTRAINT ck_task_definition_source_metadata
        CHECK (jsonb_typeof(source_metadata) = 'object'),
    CONSTRAINT ck_task_definition_schedule_config
        CHECK (jsonb_typeof(schedule_config) = 'object'),
    CONSTRAINT ck_task_definition_version
        CHECK (version >= 0)
);

CREATE TRIGGER trg_task_definition_updated_at
BEFORE UPDATE ON app.task_definition
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

COMMENT ON TABLE app.credential_profile IS 'Encrypted Bilibili credential metadata; secrets are never returned by APIs';
COMMENT ON TABLE app.task_definition IS 'Persistent desired task configuration; API serializes bigint IDs as strings';
