CREATE TABLE app.task_execution (
    execution_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL,
    trigger_type varchar(24) NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'QUEUED',
    phase varchar(32),
    attempt integer NOT NULL DEFAULT 1,
    pages_processed bigint NOT NULL DEFAULT 0,
    comments_discovered bigint NOT NULL DEFAULT 0,
    comments_inserted bigint NOT NULL DEFAULT 0,
    comments_duplicate bigint NOT NULL DEFAULT 0,
    retry_count integer NOT NULL DEFAULT 0,
    cursor_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    cancellation_requested boolean NOT NULL DEFAULT false,
    error_code varchar(64),
    error_summary text,
    trace_id varchar(64),
    worker_id varchar(128),
    queued_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    started_at timestamptz,
    heartbeat_at timestamptz,
    next_retry_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT fk_task_execution_task
        FOREIGN KEY (task_id)
        REFERENCES app.task_definition (task_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_task_execution_id_task UNIQUE (execution_id, task_id),
    CONSTRAINT ck_task_execution_trigger_type
        CHECK (trigger_type IN ('SCHEDULED', 'MANUAL', 'RECOVERY', 'CREATOR_DISCOVERY')),
    CONSTRAINT ck_task_execution_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_task_execution_phase
        CHECK (
            phase IS NULL OR phase IN (
                'RESOLVING_SOURCE',
                'FETCHING_COMMENTS',
                'PERSISTING_COMMENTS',
                'WAITING_RATE_LIMIT',
                'SCHEDULING_NEXT'
            )
        ),
    CONSTRAINT ck_task_execution_attempts
        CHECK (attempt >= 1 AND retry_count >= 0),
    CONSTRAINT ck_task_execution_counts
        CHECK (
            pages_processed >= 0
            AND comments_discovered >= 0
            AND comments_inserted >= 0
            AND comments_duplicate >= 0
        ),
    CONSTRAINT ck_task_execution_cursor_state
        CHECK (jsonb_typeof(cursor_state) = 'object')
);

CREATE TRIGGER trg_task_execution_updated_at
BEFORE UPDATE ON app.task_execution
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

CREATE TABLE app.task_event (
    event_sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint,
    execution_id bigint,
    event_type varchar(32) NOT NULL,
    message text,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT fk_task_event_task
        FOREIGN KEY (task_id)
        REFERENCES app.task_definition (task_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_task_event_execution_task
        FOREIGN KEY (execution_id, task_id)
        REFERENCES app.task_execution (execution_id, task_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_task_event_execution_task
        CHECK (execution_id IS NULL OR task_id IS NOT NULL),
    CONSTRAINT ck_task_event_type
        CHECK (event_type IN (
            'task.updated',
            'execution.updated',
            'comments.appended',
            'system.updated',
            'heartbeat'
        )),
    CONSTRAINT ck_task_event_payload
        CHECK (jsonb_typeof(payload) = 'object')
);

CREATE TABLE app.operation_audit (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor varchar(128) NOT NULL,
    action varchar(64) NOT NULL,
    target_type varchar(64),
    target_id varchar(128),
    outcome varchar(16) NOT NULL,
    trace_id varchar(64),
    source_ip inet,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT ck_operation_audit_actor CHECK (btrim(actor) <> ''),
    CONSTRAINT ck_operation_audit_action CHECK (btrim(action) <> ''),
    CONSTRAINT ck_operation_audit_outcome
        CHECK (outcome IN ('SUCCESS', 'REJECTED', 'FAILED')),
    CONSTRAINT ck_operation_audit_details
        CHECK (jsonb_typeof(details) = 'object')
);

CREATE TABLE app.idempotency_request (
    idempotency_request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_scope varchar(128) NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    request_hash varchar(64) NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'PROCESSING',
    response_status integer,
    response_body jsonb,
    resource_type varchar(64),
    resource_id varchar(128),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    completed_at timestamptz,
    expires_at timestamptz NOT NULL,
    CONSTRAINT uq_idempotency_request_scope_key
        UNIQUE (request_scope, idempotency_key),
    CONSTRAINT ck_idempotency_request_scope CHECK (btrim(request_scope) <> ''),
    CONSTRAINT ck_idempotency_request_key CHECK (btrim(idempotency_key) <> ''),
    CONSTRAINT ck_idempotency_request_hash
        CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_idempotency_request_state
        CHECK (state IN ('PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_idempotency_request_response_status
        CHECK (response_status IS NULL OR response_status BETWEEN 100 AND 599),
    CONSTRAINT ck_idempotency_request_expiry
        CHECK (expires_at > created_at)
);

CREATE TRIGGER trg_idempotency_request_updated_at
BEFORE UPDATE ON app.idempotency_request
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

COMMENT ON TABLE app.task_execution IS 'A single scheduled or manual execution with durable progress and checkpoint state';
COMMENT ON TABLE app.task_event IS 'Ordered durable event stream used to recover SSE state';
COMMENT ON TABLE app.operation_audit IS 'Sanitized administrator operation audit; secrets must never be stored in details';
COMMENT ON TABLE app.idempotency_request IS 'Idempotency-Key request ownership and replay result';
