CREATE TABLE comment_data.comment_table_template (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mid varchar(32) NOT NULL,
    uname varchar(255),
    avatar text,
    current_level smallint,
    content text,
    ctime timestamptz NOT NULL,
    rpid bigint NOT NULL,
    parent_rpid bigint,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uq_comment_table_template_rpid UNIQUE (rpid)
);

COMMENT ON TABLE comment_data.comment_table_template IS
    'Structure-only template copied into comment_task_<internal task ID> tables';

CREATE FUNCTION app.comment_table_name(p_task_id bigint)
RETURNS name
LANGUAGE plpgsql
IMMUTABLE
STRICT
SET search_path = pg_catalog, pg_temp
AS $function$
DECLARE
    v_table_name text;
BEGIN
    IF p_task_id <= 0 THEN
        RAISE EXCEPTION 'task ID must be positive'
            USING ERRCODE = '22023';
    END IF;

    v_table_name := format('comment_task_%s', p_task_id);
    IF v_table_name !~ '^comment_task_[1-9][0-9]*$' THEN
        RAISE EXCEPTION 'invalid internal comment table name'
            USING ERRCODE = '22023';
    END IF;

    RETURN v_table_name::name;
END;
$function$;

CREATE FUNCTION app.ensure_comment_table(p_task_id bigint)
RETURNS regclass
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, app, comment_data, pg_temp
AS $function$
DECLARE
    v_task_type varchar(32);
    v_table_name name;
    v_relation regclass;
    v_relation_kind "char";
BEGIN
    v_table_name := app.comment_table_name(p_task_id);
    PERFORM pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended('bilibili-comment-table:' || p_task_id::text, 0)
    );

    SELECT task.task_type
      INTO v_task_type
      FROM app.task_definition AS task
     WHERE task.task_id = p_task_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'task % does not exist', p_task_id
            USING ERRCODE = 'P0002';
    END IF;

    IF v_task_type <> 'CONTENT_COMMENTS' THEN
        RAISE EXCEPTION 'task % does not own a comment table', p_task_id
            USING ERRCODE = '22023';
    END IF;

    v_relation := pg_catalog.to_regclass(
        pg_catalog.format('%I.%I', 'comment_data', v_table_name)
    );

    IF v_relation IS NULL THEN
        EXECUTE pg_catalog.format(
            'CREATE TABLE comment_data.%I (LIKE comment_data.comment_table_template INCLUDING ALL)',
            v_table_name
        );
        v_relation := pg_catalog.to_regclass(
            pg_catalog.format('%I.%I', 'comment_data', v_table_name)
        );
    END IF;

    SELECT relation.relkind
      INTO v_relation_kind
      FROM pg_catalog.pg_class AS relation
     WHERE relation.oid = v_relation;

    IF v_relation_kind <> 'r' THEN
        RAISE EXCEPTION 'comment relation for task % is not an ordinary table', p_task_id
            USING ERRCODE = '42809';
    END IF;

    RETURN v_relation;
END;
$function$;

CREATE FUNCTION app.insert_comments(
    p_task_id bigint,
    p_comments jsonb
)
RETURNS TABLE (
    received_count bigint,
    inserted_count bigint,
    duplicate_count bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, app, comment_data, pg_temp
AS $function$
DECLARE
    v_table_name name;
    v_received_count bigint;
    v_inserted_count bigint;
BEGIN
    IF p_comments IS NULL OR pg_catalog.jsonb_typeof(p_comments) <> 'array' THEN
        RAISE EXCEPTION 'comments payload must be a JSON array'
            USING ERRCODE = '22023';
    END IF;

    IF EXISTS (
        SELECT 1
          FROM pg_catalog.jsonb_array_elements(p_comments) AS element(item)
         WHERE pg_catalog.jsonb_typeof(element.item) <> 'object'
            OR NULLIF(pg_catalog.btrim(element.item ->> 'rpid'), '') IS NULL
            OR NULLIF(pg_catalog.btrim(element.item ->> 'mid'), '') IS NULL
            OR NULLIF(pg_catalog.btrim(element.item ->> 'ctime'), '') IS NULL
    ) THEN
        RAISE EXCEPTION 'each comment must contain non-empty rpid, mid and ctime fields'
            USING ERRCODE = '22023';
    END IF;

    PERFORM app.ensure_comment_table(p_task_id);
    v_table_name := app.comment_table_name(p_task_id);
    v_received_count := pg_catalog.jsonb_array_length(p_comments);

    EXECUTE pg_catalog.format(
        $sql$
        WITH parsed AS (
            SELECT input.rpid,
                   input.mid,
                   input.uname,
                   input.avatar,
                   input.current_level,
                   input.content,
                   input.ctime,
                   input.parent_rpid
              FROM pg_catalog.jsonb_to_recordset($1) AS input(
                  rpid bigint,
                  mid text,
                  uname text,
                  avatar text,
                  current_level smallint,
                  content text,
                  ctime timestamptz,
                  parent_rpid bigint
              )
        ), inserted AS (
            INSERT INTO comment_data.%I (
                rpid,
                mid,
                uname,
                avatar,
                current_level,
                content,
                ctime,
                parent_rpid
            )
            SELECT parsed.rpid,
                   parsed.mid,
                   parsed.uname,
                   parsed.avatar,
                   parsed.current_level,
                   parsed.content,
                   parsed.ctime,
                   parsed.parent_rpid
              FROM parsed
            ON CONFLICT (rpid) DO NOTHING
            RETURNING 1
        )
        SELECT count(*)::bigint FROM inserted
        $sql$,
        v_table_name
    ) INTO v_inserted_count USING p_comments;

    RETURN QUERY
    SELECT v_received_count,
           v_inserted_count,
           v_received_count - v_inserted_count;
END;
$function$;

CREATE FUNCTION app.query_comments_page(
    p_task_id bigint,
    p_before_ctime timestamptz DEFAULT NULL,
    p_before_rpid bigint DEFAULT NULL,
    p_limit integer DEFAULT 50
)
RETURNS TABLE (
    comment_id bigint,
    mid varchar(32),
    uname varchar(255),
    avatar text,
    current_level smallint,
    content text,
    ctime timestamptz,
    rpid bigint,
    parent_rpid bigint,
    created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, app, comment_data, pg_temp
AS $function$
DECLARE
    v_table_name name;
BEGIN
    IF p_limit < 1 OR p_limit > 200 THEN
        RAISE EXCEPTION 'page limit must be between 1 and 200'
            USING ERRCODE = '22023';
    END IF;

    IF (p_before_ctime IS NULL) <> (p_before_rpid IS NULL) THEN
        RAISE EXCEPTION 'ctime and rpid cursor values must be both null or both present'
            USING ERRCODE = '22023';
    END IF;

    PERFORM app.ensure_comment_table(p_task_id);
    v_table_name := app.comment_table_name(p_task_id);

    RETURN QUERY EXECUTE pg_catalog.format(
        $sql$
        SELECT comment.comment_id,
               comment.mid,
               comment.uname,
               comment.avatar,
               comment.current_level,
               comment.content,
               comment.ctime,
               comment.rpid,
               comment.parent_rpid,
               comment.created_at
          FROM comment_data.%I AS comment
         WHERE $1::timestamptz IS NULL
            OR (comment.ctime, comment.rpid) < ($1::timestamptz, $2::bigint)
         ORDER BY comment.ctime DESC, comment.rpid DESC
         LIMIT $3
        $sql$,
        v_table_name
    ) USING p_before_ctime, p_before_rpid, p_limit;
END;
$function$;

CREATE FUNCTION app.count_task_comments(p_task_id bigint)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, app, comment_data, pg_temp
AS $function$
DECLARE
    v_table_name name;
    v_count bigint;
BEGIN
    PERFORM app.ensure_comment_table(p_task_id);
    v_table_name := app.comment_table_name(p_task_id);
    EXECUTE pg_catalog.format(
        'SELECT count(*)::bigint FROM comment_data.%I',
        v_table_name
    ) INTO v_count;
    RETURN v_count;
END;
$function$;

REVOKE ALL ON FUNCTION app.comment_table_name(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION app.ensure_comment_table(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION app.insert_comments(bigint, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app.query_comments_page(bigint, timestamptz, bigint, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION app.count_task_comments(bigint) FROM PUBLIC;

-- Deployment provisioning must explicitly grant EXECUTE on the controlled
-- functions required by the runtime role. No runtime role needs CREATE/DROP or
-- direct DML privileges in comment_data when all access goes through this API.
