CREATE TABLE app.comment_export_job (
    export_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL,
    requested_by varchar(128) NOT NULL,
    export_format varchar(16) NOT NULL,
    export_columns jsonb NOT NULL,
    filter_json jsonb NOT NULL,
    filter_hash varchar(64) NOT NULL,
    sort_order varchar(16) NOT NULL,
    snapshot_max_comment_id bigint NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'QUEUED',
    row_limit bigint NOT NULL,
    byte_limit bigint NOT NULL,
    rows_written bigint NOT NULL DEFAULT 0,
    bytes_written bigint NOT NULL DEFAULT 0,
    file_key varchar(64),
    encrypted_sha256 varchar(64),
    cancellation_requested boolean NOT NULL DEFAULT false,
    error_code varchar(64),
    error_summary text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    started_at timestamptz,
    heartbeat_at timestamptz,
    finished_at timestamptz,
    expires_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT fk_comment_export_job_task
        FOREIGN KEY (task_id)
        REFERENCES app.task_definition (task_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_comment_export_job_actor CHECK (btrim(requested_by) <> ''),
    CONSTRAINT ck_comment_export_job_format CHECK (export_format IN ('CSV', 'JSONL')),
    CONSTRAINT ck_comment_export_job_columns CHECK (jsonb_typeof(export_columns) = 'array'),
    CONSTRAINT ck_comment_export_job_filter CHECK (jsonb_typeof(filter_json) = 'object'),
    CONSTRAINT ck_comment_export_job_filter_hash
        CHECK (filter_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_comment_export_job_sort CHECK (sort_order IN ('CTIME_DESC', 'CTIME_ASC')),
    CONSTRAINT ck_comment_export_job_snapshot CHECK (snapshot_max_comment_id >= 0),
    CONSTRAINT ck_comment_export_job_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT ck_comment_export_job_limits CHECK (row_limit > 0 AND byte_limit > 0),
    CONSTRAINT ck_comment_export_job_progress CHECK (rows_written >= 0 AND bytes_written >= 0),
    CONSTRAINT ck_comment_export_job_file_key
        CHECK (file_key IS NULL OR file_key ~ '^[0-9a-f]{32}$'),
    CONSTRAINT ck_comment_export_job_digest
        CHECK (encrypted_sha256 IS NULL OR encrypted_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_comment_export_job_expiry CHECK (expires_at > created_at)
);

CREATE TRIGGER trg_comment_export_job_updated_at
BEFORE UPDATE ON app.comment_export_job
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

CREATE INDEX idx_comment_export_job_task_created
    ON app.comment_export_job (task_id, export_id DESC);

CREATE INDEX idx_comment_export_job_queue
    ON app.comment_export_job (status, export_id)
    WHERE status IN ('QUEUED', 'RUNNING');

CREATE INDEX idx_comment_export_job_expiry
    ON app.comment_export_job (expires_at, export_id)
    WHERE status IN ('SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED');

COMMENT ON TABLE app.comment_export_job IS
    'Persistent single-task comment export jobs; file_key is an internal random key, never a user path';
